# Generated by Django 5.0.4 on 2024-06-18 14:09

from django.db import migrations, models
import django.db.models.deletion

import imagesAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projectsAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original",
                    models.ImageField(
                        upload_to=imagesAPI.models.ImagePathUpload("original"),
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        upload_to=imagesAPI.models.ImagePathUpload("thumbs"),
                    ),
                ),
                (
                    "big_thumb",
                    models.ImageField(
                        upload_to=imagesAPI.models.ImagePathUpload(
                            "big_thumbs",
                        ),
                    ),
                ),
                (
                    "big_1920",
                    models.ImageField(
                        upload_to=imagesAPI.models.ImagePathUpload("big_1920"),
                    ),
                ),
                (
                    "d2500",
                    models.ImageField(
                        upload_to=imagesAPI.models.ImagePathUpload("d2500"),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("init", "иницилизация"),
                            ("uploaded", "загруженно"),
                            ("processing", "обработка"),
                            ("done", "завершенно"),
                            ("error", "ошибка"),
                        ],
                        default="init",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Выберите проект к которому"
                        " будет принадлежать изображение.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="projectsAPI.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "избражение",
                "verbose_name_plural": "изображения",
            },
        ),
    ]


__all__ = ()
