# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: testbackend CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt;
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Lint with black
        run: |
          black . --check --diff
      - name: Test requirements files
        run: |
          sort-requirements requirements/prod.txt
          sort-requirements requirements/test.txt
          sort-requirements requirements/dev.txt
      - name: Test with django test
        run: |
          cd testbackend
          python manage.py test
